services:
  - type: web
    name: data-discovery-server
    env: python
    region: oregon            # change region if desired
    branch: main
    plan: free            # choose plan (starter/free/standard)
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn DataDiscoveryServer:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        value: supersecretkey123
      - key: SECRET_KEY
        value: super-secret-key
databases:
  - name: pii-data
    region: oregon
    plan: starter