services:
  - type: web
    name: data-discovery-server
    env: python
    region: oregon            # change region if desired
    branch: main
    plan: starter            # choose plan (starter/free/standard)
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker DataDiscoveryServer:app --bind 0.0.0.0:$PORT
    envVars:
      - key: API_KEY
        value: supersecretkey123
      - key: SECRET_KEY
        value: super-secret-key
databases:
  - name: pii-data
    region: oregon
    plan: starter